# Generated by Django 3.2 on 2021-05-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('item', 'cart')},
        ),
    ]
