# Generated by Django 3.2 on 2021-05-16 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0002_alter_cartitem_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('delivery_at', models.DateTimeField(null=True)),
                ('address', models.CharField(max_length=256)),
                ('status', models.CharField(
                    choices=[
                        ('created', 'создан'),
                        ('delivered', 'доставлен'),
                        ('processed', 'обработан'),
                        ('cancelled', 'отменен'),
                    ],
                    max_length=9),
                 ),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='orders', to='carts.cart')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
